controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    eef_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
eef_controller:
  ros__parameters:
    joints:
      - finger_joint1
      # - finger_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity